apiVersion: v1
kind: ConfigMap
metadata:
  name: diploma-orchestrator-api-config
  namespace: {{ .Release.Namespace }}
data:
  ORCHESTRATOR_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  ORCHESTRATOR_BACKUP_IMAGE_REGISTRY: {{ .Values.config.backupImage.registry | quote }}
  ORCHESTRATOR_BACKUP_IMAGE_REPOSITORY: {{ .Values.config.backupImage.repository | quote }}
  ORCHESTRATOR_BACKUP_IMAGE_TAG: {{ .Values.config.backupImage.tag | quote }}
  ORCHESTRATOR_BACKUP_IMAGE_PULL_POLICY: {{ .Values.config.backupImage.pullPolicy | quote }}
