apiVersion: v1
kind: Secret
metadata:
  name: diploma-orchestrator-api-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ORCHESTRATOR_ENCRYPTION_KEY: {{ .Values.secret.encryptionKey | quote }}
  kubeconfig: |
{{ .Values.secret.kubeconfig | indent 4 }}
