apiVersion: v1
kind: Secret
metadata:
  name: diploma-orchestrator-api-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  kubeconfig: |
{{ .Values.secret.kubeconfig | indent 4 }}
