apiVersion: v1
kind: ConfigMap
metadata:
  name: diploma-orchestrator-ui-config
  namespace: {{ .Release.Namespace }}
data:
  env.js: |
    window.__APP_CONFIG__ = {
      API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
    };
