apiVersion: v1
kind: Service
metadata:
  name: diploma-orchestrator-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: diploma-orchestrator-ui
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
