apiVersion: v1
kind: ConfigMap
metadata:
  name: diploma-orchestrator-event-watcher-config
  namespace: {{ .Release.Namespace }}
data:
  ORCHESTRATOR_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  ORCHESTRATOR_DB_BACKUPPER_IMAGE_REGISTRY: {{ .Values.config.dbBackupper.image.registry | quote }}
  ORCHESTRATOR_DB_BACKUPPER_IMAGE_REPOSITORY: {{ .Values.config.dbBackupper.image.repository | quote }}
  ORCHESTRATOR_DB_BACKUPPER_IMAGE_TAG: {{ .Values.config.dbBackupper.image.tag | quote }}
  ORCHESTRATOR_DB_BACKUPPER_IMAGE_PULL_POLICY: {{ .Values.config.dbBackupper.image.pullPolicy | quote }}
  ORCHESTRATOR_DB_BACKUPPER_CHART_REPOSITORY_URL: {{ .Values.config.dbBackupper.chart.repositoryUrl | quote }}
  ORCHESTRATOR_DB_BACKUPPER_CHART_REF: {{ .Values.config.dbBackupper.chart.ref | quote }}
  ORCHESTRATOR_DB_BACKUPPER_CHART_PATH: {{ .Values.config.dbBackupper.chart.path | quote }}
  ORCHESTRATOR_DB_RESTORER_IMAGE_REGISTRY: {{ .Values.config.dbRestorer.image.registry | quote }}
  ORCHESTRATOR_DB_RESTORER_IMAGE_REPOSITORY: {{ .Values.config.dbRestorer.image.repository | quote }}
  ORCHESTRATOR_DB_RESTORER_IMAGE_TAG: {{ .Values.config.dbRestorer.image.tag | quote }}
  ORCHESTRATOR_DB_RESTORER_IMAGE_PULL_POLICY: {{ .Values.config.dbRestorer.image.pullPolicy | quote }}
  ORCHESTRATOR_DB_RESTORER_CHART_REPOSITORY_URL: {{ .Values.config.dbRestorer.chart.repositoryUrl | quote }}
  ORCHESTRATOR_DB_RESTORER_CHART_REF: {{ .Values.config.dbRestorer.chart.ref | quote }}
  ORCHESTRATOR_DB_RESTORER_CHART_PATH: {{ .Values.config.dbRestorer.chart.path | quote }}
  ORCHESTRATOR_S3_BACKUPPER_IMAGE_REGISTRY: {{ .Values.config.s3Backupper.image.registry | quote }}
  ORCHESTRATOR_S3_BACKUPPER_IMAGE_REPOSITORY: {{ .Values.config.s3Backupper.image.repository | quote }}
  ORCHESTRATOR_S3_BACKUPPER_IMAGE_TAG: {{ .Values.config.s3Backupper.image.tag | quote }}
  ORCHESTRATOR_S3_BACKUPPER_IMAGE_PULL_POLICY: {{ .Values.config.s3Backupper.image.pullPolicy | quote }}
  ORCHESTRATOR_S3_BACKUPPER_CHART_REPOSITORY_URL: {{ .Values.config.s3Backupper.chart.repositoryUrl | quote }}
  ORCHESTRATOR_S3_BACKUPPER_CHART_REF: {{ .Values.config.s3Backupper.chart.ref | quote }}
  ORCHESTRATOR_S3_BACKUPPER_CHART_PATH: {{ .Values.config.s3Backupper.chart.path | quote }}
  ORCHESTRATOR_S3_RESTORER_IMAGE_REGISTRY: {{ .Values.config.s3Restorer.image.registry | quote }}
  ORCHESTRATOR_S3_RESTORER_IMAGE_REPOSITORY: {{ .Values.config.s3Restorer.image.repository | quote }}
  ORCHESTRATOR_S3_RESTORER_IMAGE_TAG: {{ .Values.config.s3Restorer.image.tag | quote }}
  ORCHESTRATOR_S3_RESTORER_IMAGE_PULL_POLICY: {{ .Values.config.s3Restorer.image.pullPolicy | quote }}
  ORCHESTRATOR_S3_RESTORER_CHART_REPOSITORY_URL: {{ .Values.config.s3Restorer.chart.repositoryUrl | quote }}
  ORCHESTRATOR_S3_RESTORER_CHART_REF: {{ .Values.config.s3Restorer.chart.ref | quote }}
  ORCHESTRATOR_S3_RESTORER_CHART_PATH: {{ .Values.config.s3Restorer.chart.path | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_IMAGE_REGISTRY: {{ .Values.config.envSynchronizer.image.registry | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_IMAGE_REPOSITORY: {{ .Values.config.envSynchronizer.image.repository | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_IMAGE_TAG: {{ .Values.config.envSynchronizer.image.tag | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_IMAGE_PULL_POLICY: {{ .Values.config.envSynchronizer.image.pullPolicy | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_CHART_REPOSITORY_URL: {{ .Values.config.envSynchronizer.chart.repositoryUrl | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_CHART_REF: {{ .Values.config.envSynchronizer.chart.ref | quote }}
  ORCHESTRATOR_ENV_SYNCHRONIZER_CHART_PATH: {{ .Values.config.envSynchronizer.chart.path | quote }}
  ORCHESTRATOR_MINIO_ENDPOINT_URL: {{ .Values.config.minio.endpointUrl | quote }}
  ORCHESTRATOR_MINIO_ACCESS_KEY_ID: {{ .Values.config.minio.accessKeyId | quote }}
  ORCHESTRATOR_MINIO_SECRET_ACCESS_KEY: {{ .Values.config.minio.secretAccessKey | quote }}
  ORCHESTRATOR_MINIO_BUCKET_NAME: {{ .Values.config.minio.bucketName | quote }}
  ORCHESTRATOR_MINIO_REGION: {{ .Values.config.minio.region | quote }}
  ORCHESTRATOR_EVENT_WATCHER_ENABLED: {{ .Values.config.eventWatcher.enabled | quote }}
  ORCHESTRATOR_EVENT_WATCHER_POLL_INTERVAL_SECONDS: {{ .Values.config.eventWatcher.pollIntervalSeconds | quote }}
  ORCHESTRATOR_EVENT_WATCHER_COOLDOWN_SECONDS: {{ .Values.config.eventWatcher.cooldownSeconds | quote }}
